# Generated by Django 4.2.1 on 2025-04-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollNumber', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=15)),
            ],
        ),
    ]
